package br.com.aj_sistemas.logistica.view;

import br.com.aj_sistemas.logistica.controller.MotoristaController;
import java.util.ArrayList;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import br.com.aj_sistemas.logistica.model.MotoristaModel;
import br.com.aj_sistemas.logistica.utils.GeradorDeRelatorio;
import javax.swing.ImageIcon;

/**
 *
 * @author Alisson Jaques
 */
public class MotoristaView extends javax.swing.JInternalFrame {

    /**
     * Creates new form MotoristaView
     */
    public MotoristaView() {
        this.setFrameIcon(new ImageIcon("src\\br\\com\\aj_sistemas\\logistica\\img\\truck-icon.png"));
        initComponents();
        preencherTabela();
    }

    private void preencherTabela() {
        MotoristaController controle = new MotoristaController();
        ArrayList<MotoristaModel> lista = controle.selecionarTodos();
        DefaultTableModel modelo = (DefaultTableModel) getJtMotorista().getModel();
        modelo.setRowCount(0);
        lista.forEach((f) -> {
            modelo.addRow(new Object[]{
                f.getIdMotorista(),
                f.getNome(),
                f.getCnh(),
                f.getIdade()
            });
        });
    }

    public void limparCampos() {
        getJtxIdMotorista().setText("");
        getJtxIdMotorista1().setText("");
        getJtxNome().setText("");
        getJtxCNH().setText("");
        getJtxIdade().setText("");
        getJbEditar().setEnabled(false);
        getJbExcluir().setEnabled(false);
        getJbInserir().setEnabled(true);
    }

    public boolean verificarCampos() {
        if (getJtxIdMotorista().getText().equals("")) {
            return true;
        } else if (getJtxNome().getText().equals("")) {
            return true;
        } else if (getJtxCNH().getText().equals("")) {
            return true;
        } else if (getJtxIdade().getText().equals("")) {
            return true;
        } else {
            return false;
        }
    }

    public boolean verifica() {
        if (getJtxNome().getText().equals("")) {
            return true;
        } else if (getJtxCNH().getText().equals("")) {
            return true;
        } else return getJtxIdade().getText().equals("");
    }

    public void requisitaFoco() {
        if (getJtxIdMotorista().getText().equals("")) {
            getJtxIdMotorista().requestFocus();
        } else if (getJtxNome().getText().equals("")) {
            getJtxNome().requestFocus();
        } else if (getJtxCNH().getText().equals("")) {
            getJtxCNH().requestFocus();
        } else {
            getJtxIdade().requestFocus();
        }
    }

    public boolean verificaId(String idMotorista) {
        if (getJtxIdMotorista().getText().equals("")) {
            return false;
        } else {
            MotoristaController controle = new MotoristaController();
            ArrayList<MotoristaModel> lista = controle.selecionarTodos();
            if (lista.stream().anyMatch((motorista) -> (motorista.getIdMotorista() == Integer.parseInt(idMotorista)))) {
                return true;
            }
        }

        return false;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jlIdMotorista = new javax.swing.JLabel();
        jlNome = new javax.swing.JLabel();
        jlCNH = new javax.swing.JLabel();
        jlIdade = new javax.swing.JLabel();
        jtxIdMotorista = new javax.swing.JTextField();
        jtxNome = new javax.swing.JTextField();
        jtxCNH = new javax.swing.JTextField();
        jtxIdade = new javax.swing.JTextField();
        jbInserir = new javax.swing.JButton();
        jbEditar = new javax.swing.JButton();
        jbExcluir = new javax.swing.JButton();
        jbSelecionar = new javax.swing.JButton();
        jbRelatorio = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtMotorista = new javax.swing.JTable();
        jbLimpar = new javax.swing.JButton();
        jtxIdMotorista1 = new javax.swing.JTextField();
        jlSelecionar = new javax.swing.JLabel();
        jbSair = new javax.swing.JButton();

        setIconifiable(true);
        setTitle("Cadastro de Motorista");
        setVisible(true);

        jPanel1.setForeground(new java.awt.Color(204, 204, 255));

        jlIdMotorista.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlIdMotorista.setText("Id Motorista:");

        jlNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlNome.setText("Nome:");

        jlCNH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlCNH.setText("CNH:");

        jlIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlIdade.setText("Idade:");

        jtxIdMotorista.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtxNome.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxNomeActionPerformed(evt);
            }
        });

        jtxCNH.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N

        jtxIdade.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxIdade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtxIdadeActionPerformed(evt);
            }
        });

        jbInserir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbInserir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/add_16.png"))); // NOI18N
        jbInserir.setText("Inserir");
        jbInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbInserirActionPerformed(evt);
            }
        });

        jbEditar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbEditar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/edit_16.png"))); // NOI18N
        jbEditar.setText("Editar");
        jbEditar.setEnabled(false);
        jbEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbEditarActionPerformed(evt);
            }
        });

        jbExcluir.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbExcluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/Cancel.png"))); // NOI18N
        jbExcluir.setText("Excluir");
        jbExcluir.setEnabled(false);
        jbExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbExcluirActionPerformed(evt);
            }
        });

        jbSelecionar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbSelecionar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/Search.png"))); // NOI18N
        jbSelecionar.setText("Selecionar");
        jbSelecionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSelecionarActionPerformed(evt);
            }
        });

        jbRelatorio.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbRelatorio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/ico_pdf.png"))); // NOI18N
        jbRelatorio.setText("Relatorio");
        jbRelatorio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbRelatorioActionPerformed(evt);
            }
        });

        jtMotorista.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtMotorista.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Id Motorista", "Nome", "CNH", "Idade"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtMotorista.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtMotoristaMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtMotorista);

        jbLimpar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbLimpar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/limpar-limpo.png"))); // NOI18N
        jbLimpar.setText("Limpar Campos");
        jbLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbLimparActionPerformed(evt);
            }
        });

        jtxIdMotorista1.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jtxIdMotorista1.setEnabled(false);

        jlSelecionar.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jlSelecionar.setText("Selecionar Pelo ID:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlNome, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlIdMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jtxIdMotorista1, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jlSelecionar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jtxIdMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jbSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jbInserir, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(jtxCNH, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jtxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, 116, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(110, 110, 110)
                                .addComponent(jbEditar)
                                .addGap(30, 30, 30)
                                .addComponent(jbExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(26, 26, 26)
                                .addComponent(jbRelatorio, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(30, 30, 30)
                                .addComponent(jbLimpar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addGap(30, 30, 30))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdMotorista)
                    .addComponent(jtxIdMotorista, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jbSelecionar)
                    .addComponent(jtxIdMotorista1, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlSelecionar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNome)
                    .addComponent(jtxNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCNH)
                    .addComponent(jtxCNH, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlIdade)
                    .addComponent(jtxIdade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jbInserir)
                    .addComponent(jbEditar)
                    .addComponent(jbExcluir)
                    .addComponent(jbRelatorio)
                    .addComponent(jbLimpar, javax.swing.GroupLayout.PREFERRED_SIZE, 29, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 235, Short.MAX_VALUE))
        );

        jbSair.setFont(new java.awt.Font("Dialog", 0, 14)); // NOI18N
        jbSair.setIcon(new javax.swing.ImageIcon(getClass().getResource("/br/com/aj_sistemas/logistica/img/close.png"))); // NOI18N
        jbSair.setText("Sair");
        jbSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jbSairActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jbSair, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(44, 44, 44))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jbSair)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtxNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxNomeActionPerformed

    private void jtxIdadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtxIdadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtxIdadeActionPerformed

    private void jbInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbInserirActionPerformed
        if (verifica()) {
            JOptionPane.showMessageDialog(this, "Favor preencher todos os campos para inserir!");
            requisitaFoco();
        } else {
            if (verificaId(getJtxIdMotorista().getText())) {
                JOptionPane.showMessageDialog(this, "Já existe motorista cadastrado com esse ID!");
            } else {
                MotoristaModel motorista = new MotoristaModel();
                if (!getJtxIdMotorista().getText().equals("")) {
                    motorista.setIdMotorista(Integer.parseInt(getJtxIdMotorista().getText()));
                }
                motorista.setNome(getJtxNome().getText());
                motorista.setCnh(getJtxCNH().getText());
                motorista.setIdade(Integer.parseInt(getJtxIdade().getText()));

                MotoristaController controle = new MotoristaController();
                if (controle.inserirComProcedure(motorista)) {
                    JOptionPane.showMessageDialog(this, "Inserido com sucesso!");
                } else {
                    JOptionPane.showMessageDialog(this, "Erro ao inserir!");
                }

                preencherTabela();
                limparCampos();
            }
        }
    }//GEN-LAST:event_jbInserirActionPerformed

    private void jbEditarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbEditarActionPerformed
        if (verificarCampos()) {
            JOptionPane.showMessageDialog(this, "Selecione um motorista para poder editar.");
            requisitaFoco();
        } else {
            MotoristaModel motorista = new MotoristaModel();
            motorista.setIdMotorista(Integer.parseInt(getJtxIdMotorista().getText()));
            motorista.setNome(getJtxNome().getText());
            motorista.setCnh(getJtxCNH().getText());
            motorista.setIdade(Integer.parseInt(getJtxIdade().getText()));

            MotoristaController controle = new MotoristaController();
            if (controle.editarComProcedure(motorista)) {
                JOptionPane.showMessageDialog(this, "Editado com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao editar!");
            }
            preencherTabela();
            limparCampos();
            getJbEditar().setEnabled(false);
            getJbExcluir().setEnabled(false);
            getJbInserir().setEnabled(true);
            getJbRelatorio().setEnabled(true);
            getJbLimpar().setEnabled(true);
            getJtxIdMotorista().setEnabled(true);
            getJbSelecionar().setEnabled(true);
        }
    }//GEN-LAST:event_jbEditarActionPerformed

    private void jbExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbExcluirActionPerformed
        if (verificarCampos()) {
            JOptionPane.showMessageDialog(this, "Selecione um motorista para poder excluir.");
            requisitaFoco();
        } else {
            MotoristaModel motorista = new MotoristaModel();
            motorista.setIdMotorista(Integer.parseInt(getJtxIdMotorista().getText()));

            MotoristaController controle = new MotoristaController();
            if (controle.excluir(motorista)) {
                JOptionPane.showMessageDialog(this, "Excluido com sucesso!");
            } else {
                JOptionPane.showMessageDialog(this, "Erro ao excluir!");
            }
            preencherTabela();
            limparCampos();
            getJbEditar().setEnabled(false);
            getJbExcluir().setEnabled(false);
            getJbInserir().setEnabled(true);
            getJbRelatorio().setEnabled(true);
            getJbLimpar().setEnabled(true);
            getJtxIdMotorista().setEnabled(true);
            getJbSelecionar().setEnabled(true);
        }
    }//GEN-LAST:event_jbExcluirActionPerformed

    private void jbSelecionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSelecionarActionPerformed
        if (getJtxIdMotorista().getText().equals("")) {
            JOptionPane.showMessageDialog(this, "Campo vazio, informe um campo válido!");
            getJtxIdMotorista().requestFocus();
        } else {
            MotoristaModel motorista = new MotoristaModel();
            motorista.setIdMotorista(Integer.parseInt(getJtxIdMotorista().getText()));

            MotoristaController controle = new MotoristaController();
            motorista = controle.selecionar(motorista);
            if (motorista != null) {
                getJtxIdMotorista().setText(String.valueOf(motorista.getIdMotorista()));
                getJtxIdMotorista1().setText(String.valueOf(motorista.getIdMotorista()));
                getJtxCNH().setText(motorista.getCnh());
                getJtxNome().setText(motorista.getNome());
                getJtxIdade().setText(String.valueOf(motorista.getIdade()));
                //getJbInserir().setEnabled(false);
                getJbEditar().setEnabled(true);
                getJbExcluir().setEnabled(true);
                getJbInserir().setEnabled(false);
            } else {
                JOptionPane.showMessageDialog(this, "ID Não encontrado!");
            }

        }
    }//GEN-LAST:event_jbSelecionarActionPerformed

    private void jbRelatorioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbRelatorioActionPerformed
        GeradorDeRelatorio r = new GeradorDeRelatorio();
        try{
            r.relatorio("RelatorioMotoristasCadastrados", "", "");
        } catch(Exception e){
            JOptionPane.showMessageDialog(this, e.getMessage(), "Alerta", 2);            
        }        
    }//GEN-LAST:event_jbRelatorioActionPerformed

    private void jtMotoristaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtMotoristaMouseClicked
        if (evt.getClickCount() == 2) {
            getJbEditar().setEnabled(true);
            getJbExcluir().setEnabled(true);
            getJbInserir().setEnabled(false);
            getJbRelatorio().setEnabled(false);
            getJbLimpar().setEnabled(false);
            getJtxIdMotorista().setEnabled(false);
            getJbSelecionar().setEnabled(false);
            int linha = getJtMotorista().getSelectedRow();
            getJtxIdMotorista().setText(String.valueOf(getJtMotorista().getValueAt(linha, 0)));
            getJtxIdMotorista1().setText(String.valueOf(getJtMotorista().getValueAt(linha, 0)));
            getJtxCNH().setText(String.valueOf(getJtMotorista().getValueAt(linha, 2)));
            getJtxNome().setText(String.valueOf(getJtMotorista().getValueAt(linha, 1)));
            getJtxIdade().setText(String.valueOf(getJtMotorista().getValueAt(linha, 3)));
        }
    }//GEN-LAST:event_jtMotoristaMouseClicked

    private void jbSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbSairActionPerformed
        int op = JOptionPane.showConfirmDialog(this, "Deseja mesmo sair?", "Sair", JOptionPane.OK_CANCEL_OPTION);

        if (op == 0) {
            dispose();
        }
    }//GEN-LAST:event_jbSairActionPerformed

    private void jbLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jbLimparActionPerformed
        limparCampos();
    }//GEN-LAST:event_jbLimparActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton jbEditar;
    private javax.swing.JButton jbExcluir;
    private javax.swing.JButton jbInserir;
    private javax.swing.JButton jbLimpar;
    private javax.swing.JButton jbRelatorio;
    private javax.swing.JButton jbSair;
    private javax.swing.JButton jbSelecionar;
    private javax.swing.JLabel jlCNH;
    private javax.swing.JLabel jlIdMotorista;
    private javax.swing.JLabel jlIdade;
    private javax.swing.JLabel jlNome;
    private javax.swing.JLabel jlSelecionar;
    private javax.swing.JTable jtMotorista;
    private javax.swing.JTextField jtxCNH;
    private javax.swing.JTextField jtxIdMotorista;
    private javax.swing.JTextField jtxIdMotorista1;
    private javax.swing.JTextField jtxIdade;
    private javax.swing.JTextField jtxNome;
    // End of variables declaration//GEN-END:variables

    /**
     * @return the jPanel1
     */
    public javax.swing.JPanel getjPanel1() {
        return jPanel1;
    }

    /**
     * @param jPanel1 the jPanel1 to set
     */
    public void setjPanel1(javax.swing.JPanel jPanel1) {
        this.jPanel1 = jPanel1;
    }

    /**
     * @return the jScrollPane1
     */
    public javax.swing.JScrollPane getjScrollPane1() {
        return jScrollPane1;
    }

    /**
     * @param jScrollPane1 the jScrollPane1 to set
     */
    public void setjScrollPane1(javax.swing.JScrollPane jScrollPane1) {
        this.jScrollPane1 = jScrollPane1;
    }

    /**
     * @return the jbEditar
     */
    public javax.swing.JButton getJbEditar() {
        return jbEditar;
    }

    /**
     * @param jbEditar the jbEditar to set
     */
    public void setJbEditar(javax.swing.JButton jbEditar) {
        this.jbEditar = jbEditar;
    }

    /**
     * @return the jbExcluir
     */
    public javax.swing.JButton getJbExcluir() {
        return jbExcluir;
    }

    /**
     * @param jbExcluir the jbExcluir to set
     */
    public void setJbExcluir(javax.swing.JButton jbExcluir) {
        this.jbExcluir = jbExcluir;
    }

    /**
     * @return the jbInserir
     */
    public javax.swing.JButton getJbInserir() {
        return jbInserir;
    }

    /**
     * @param jbInserir the jbInserir to set
     */
    public void setJbInserir(javax.swing.JButton jbInserir) {
        this.jbInserir = jbInserir;
    }

    /**
     * @return the jbRelatorio
     */
    public javax.swing.JButton getJbRelatorio() {
        return jbRelatorio;
    }

    /**
     * @param jbRelatorio the jbRelatorio to set
     */
    public void setJbRelatorio(javax.swing.JButton jbRelatorio) {
        this.jbRelatorio = jbRelatorio;
    }

    /**
     * @return the jbSair
     */
    public javax.swing.JButton getJbSair() {
        return jbSair;
    }

    /**
     * @param jbSair the jbSair to set
     */
    public void setJbSair(javax.swing.JButton jbSair) {
        this.jbSair = jbSair;
    }

    /**
     * @return the jbSelecionar
     */
    public javax.swing.JButton getJbSelecionar() {
        return jbSelecionar;
    }

    /**
     * @param jbSelecionar the jbSelecionar to set
     */
    public void setJbSelecionar(javax.swing.JButton jbSelecionar) {
        this.jbSelecionar = jbSelecionar;
    }

    /**
     * @return the jlCNH
     */
    public javax.swing.JLabel getJlCNH() {
        return jlCNH;
    }

    /**
     * @param jlCNH the jlCNH to set
     */
    public void setJlCNH(javax.swing.JLabel jlCNH) {
        this.jlCNH = jlCNH;
    }

    /**
     * @return the jlIdMotorista
     */
    public javax.swing.JLabel getJlIdMotorista() {
        return jlIdMotorista;
    }

    /**
     * @param jlIdMotorista the jlIdMotorista to set
     */
    public void setJlIdMotorista(javax.swing.JLabel jlIdMotorista) {
        this.jlIdMotorista = jlIdMotorista;
    }

    /**
     * @return the jlIdade
     */
    public javax.swing.JLabel getJlIdade() {
        return jlIdade;
    }

    /**
     * @param jlIdade the jlIdade to set
     */
    public void setJlIdade(javax.swing.JLabel jlIdade) {
        this.jlIdade = jlIdade;
    }

    /**
     * @return the jlNome
     */
    public javax.swing.JLabel getJlNome() {
        return jlNome;
    }

    /**
     * @param jlNome the jlNome to set
     */
    public void setJlNome(javax.swing.JLabel jlNome) {
        this.jlNome = jlNome;
    }

    /**
     * @return the jtMotorista
     */
    public javax.swing.JTable getJtMotorista() {
        return jtMotorista;
    }

    /**
     * @param jtMotorista the jtMotorista to set
     */
    public void setJtMotorista(javax.swing.JTable jtMotorista) {
        this.jtMotorista = jtMotorista;
    }

    /**
     * @return the jtxCNH
     */
    public javax.swing.JTextField getJtxCNH() {
        return jtxCNH;
    }

    /**
     * @param jtxCNH the jtxCNH to set
     */
    public void setJtxCNH(javax.swing.JTextField jtxCNH) {
        this.jtxCNH = jtxCNH;
    }

    /**
     * @return the jtxIdFilme
     */
    public javax.swing.JTextField getJtxIdMotorista() {
        return jtxIdMotorista;
    }

    /**
     * @param jtxIdFilme the jtxIdFilme to set
     */
    public void setJtxIdMotorista(javax.swing.JTextField jtxIdMotorista) {
        this.jtxIdMotorista = jtxIdMotorista;
    }

    /**
     * @return the jtxIdade
     */
    public javax.swing.JTextField getJtxIdade() {
        return jtxIdade;
    }

    /**
     * @param jtxIdade the jtxIdade to set
     */
    public void setJtxIdade(javax.swing.JTextField jtxIdade) {
        this.jtxIdade = jtxIdade;
    }

    /**
     * @return the jtxNome
     */
    public javax.swing.JTextField getJtxNome() {
        return jtxNome;
    }

    /**
     * @param jtxNome the jtxNome to set
     */
    public void setJtxNome(javax.swing.JTextField jtxNome) {
        this.jtxNome = jtxNome;
    }

    /**
     * @return the jbLimpar
     */
    public javax.swing.JButton getJbLimpar() {
        return jbLimpar;
    }

    /**
     * @param jbLimpar the jbLimpar to set
     */
    public void setJbLimpar(javax.swing.JButton jbLimpar) {
        this.jbLimpar = jbLimpar;
    }

    /**
     * @return the jtxIdMotorista1
     */
    public javax.swing.JTextField getJtxIdMotorista1() {
        return jtxIdMotorista1;
    }

    /**
     * @param jtxIdMotorista1 the jtxIdMotorista1 to set
     */
    public void setJtxIdMotorista1(javax.swing.JTextField jtxIdMotorista1) {
        this.jtxIdMotorista1 = jtxIdMotorista1;
    }

}
